services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./docker/clickhouse:/etc/clickhouse-server/config.d
      - ./docker/logs/clickhouse:/var/log/clickhouse-server
    depends_on:
      - keeper
    restart: unless-stopped

  keeper:
    image: clickhouse/clickhouse-keeper:latest
    ports:
      - "9181:9181"
    volumes:
      - keeper_data:/var/lib/clickhouse-keeper
      - ./docker/keeper:/etc/clickhouse-keeper
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:1.64.0
    command:
      - "--memory.max-traces=25000"
      - "--query.base-path=/jaeger/ui"
    restart: unless-stopped
    ports:
      - "16686:16686"
      - "14268:14268"
      - "4317:4317"
      - "4318:4318"

  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    restart: unless-stopped
    environment:
      - "GF_INSTALL_PLUGINS=vertamedia-clickhouse-datasource"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
    depends_on:
      - clickhouse

  # collector:
  #   image: otel/opentelemetry-collector-contrib:0.102.1
  #   restart: unless-stopped
  #   command: [ "--config=/etc/config.yml" ]
  #   volumes:
  #     - ./docker/collector/config.yml:/etc/config.yml
  #   ports:
  #     - "4317"
  #     - "4318"
  #   depends_on:
  #     - jaeger

volumes:
  keeper_data:
  clickhouse_data:
  grafana_data:
  prometheus_data:
