services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./docker/config.d:/etc/clickhouse-server/config.d
      - ./docker/logs/clickhouse:/var/log/clickhouse-server
    environment:
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    depends_on:
      - keeper
    restart: unless-stopped

  keeper:
    image: clickhouse/clickhouse-keeper:latest
    ports:
      - "9181:9181"
    volumes:
      - keeper_data:/var/lib/clickhouse-keeper
      - ./docker/keeper.d:/etc/clickhouse-keeper
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    restart: unless-stopped
    environment:
      - "GF_INSTALL_PLUGINS=vertamedia-clickhouse-datasource"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"

volumes:
  keeper_data:
  clickhouse_data:
  grafana_data:
