apiVersion: 1

datasources:
  - name: ClickHouse
    type: vertamedia-clickhouse-datasource
    access: proxy
    url: http://clickhouse-01:8123
    user: grafana
    secureJsonData:
      password: grafana
    jsonData:
      defaultDatabase: default
      addCorsHeader: false
      usePOST: true
      useYandexClusterNameForGlobalInWhere: false
      xHeaderUser: grafana
      xHeaderKey: grafana
    editable: true
    isDefault: true