zookeeper:
  node:
    host: keeper
    port: 9181
listen_host: "0.0.0.0"
opentelemetry_span_log:
  engine: "ENGINE MergeTree PARTITION BY toYYYYMM(finish_date) ORDER BY (finish_date, finish_time_us, trace_id)"
  database: system
  table: opentelemetry_span_log
  flush_interval_milliseconds: 7500
  max_size_rows: 1048576
  reserved_size_rows: 8192
  buffer_size_rows_flush_threshold: 524288
  flush_on_crash: false
profiles:
  - name: default
    opentelemetry_start_trace_probability: 1
