{
 "title": "ClickHouse Otel Demo",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "traceId",
    "label": "traceId",
    "query": "SELECT TraceId FROM otel_traces_trace_id_ts"
   },
   {
    "name": "datasource",
    "label": "datasource",
    "query": "vertamedia-clickhouse-datasource"
   }
  ]
 },
 "panels": [
  {
   "title": "Traces",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "FLOAT",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "rawQuery": "/* grafana dashboard=ClickHouse Otel Demo, user=1 */\nSELECT (intDiv(Timestamp * 1000, (5 * 1000)) * (5 * 1000)) as t, count() FROM default.otel_traces WHERE Timestamp >= 1738317941 AND Timestamp <= 1738328741 GROUP BY t ORDER BY t",
     "rawSql": "SELECT\r\n  min(Timestamp) as timestamp,\r\n  TraceId as `Trace ID`,\r\n  argMin(ServiceName, Timestamp) as `Service Name`,\r\n  divide(max(Duration), 1000000) as Duration\r\nFROM otel_traces\r\nWHERE\r\n  $__conditionalAll(TraceId IN (${trace_id:singlequote}),  $trace_id)\r\n  AND ServiceName IN (${serviceName:singlequote})\r\n  AND ServiceName != 'loadgenerator'\r\n  AND $__timeFilter(Timestamp)\r\nGROUP BY TraceId\r\nORDER BY Duration DESC\r\nLIMIT 100\r\n",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Traced query",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT max(attribute['db.statement']) AS sql, \r\n       toDateTime(min(start_time_us / 1000 / 1000)) as StartTime,\r\n       (min(start_time_us) - max(finish_time_us)) / 1000 / 1000 as Duration\r\nFROM system.opentelemetry_span_log\r\nWHERE trace_id = '$traceId' ",
     "rawQuery": "/* grafana dashboard=ClickHouse Otel Demo, user=1 */\nSELECT max(attribute['db.statement']) AS sql, \r\n       toDateTime(min(start_time_us / 1000 / 1000)) as StartTime,\r\n       (min(start_time_us) - max(finish_time_us)) / 1000 / 1000 as Duration\r\nFROM system.opentelemetry_span_log\r\nWHERE trace_id = 'db7f4d2a-0a7b-f512-2e0c-e587807015b9'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Trace detail",
   "type": "traces",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "system",
     "dateColDataType": "finish_date",
     "dateTimeColDataType": "start_time_us",
     "dateTimeType": "TIMESTAMP64_9",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "WITH 'a9bee065-3c7d-13b3-8471-8e5b44324a75' as trace_id,\r\n  (SELECT min(Start) FROM \"default\".\"otel_traces_trace_id_ts\"\r\n    WHERE TraceId = trace_id) as trace_start,\r\n  (SELECT max(End) + 1 FROM \"default\".\"otel_traces_trace_id_ts\"\r\n    WHERE TraceId = trace_id) as trace_end\r\nSELECT \"TraceId\" as traceID,\r\n  \"SpanId\" as spanID,\r\n  \"ParentSpanId\" as parentSpanID,\r\n  \"ServiceName\" as serviceName,\r\n  \"SpanName\" as operationName,\r\n  \"Timestamp\" as startTime,\r\n  multiply(\"Duration\", 0.000001) as duration,\r\n  arrayMap(key -> map('key', key, 'value',\"SpanAttributes\"[key]),\r\n  mapKeys(\"SpanAttributes\")) as tags,\r\n  arrayMap(key -> map('key', key, 'value',\"ResourceAttributes\"[key]),\r\n  mapKeys(\"ResourceAttributes\")) as serviceTags\r\nFROM \"default\".\"otel_traces\"\r\nWHERE traceID = trace_id\r\n  AND startTime >= trace_start\r\n  AND startTime <= trace_end\r\nORDER BY startTime\r\nLIMIT 1000",
     "rawQuery": "/* grafana dashboard=ClickHouse Otel Demo, user=1 */\nWITH 'a9bee065-3c7d-13b3-8471-8e5b44324a75' as trace_id,\r\n  (SELECT min(Start) FROM \"default\".\"otel_traces_trace_id_ts\"\r\n    WHERE TraceId = trace_id) as trace_start,\r\n  (SELECT max(End) + 1 FROM \"default\".\"otel_traces_trace_id_ts\"\r\n    WHERE TraceId = trace_id) as trace_end\r\nSELECT \"TraceId\" as traceID,\r\n  \"SpanId\" as spanID,\r\n  \"ParentSpanId\" as parentSpanID,\r\n  \"ServiceName\" as serviceName,\r\n  \"SpanName\" as operationName,\r\n  \"Timestamp\" as startTime,\r\n  multiply(\"Duration\", 0.000001) as duration,\r\n  arrayMap(key -> map('key', key, 'value',\"SpanAttributes\"[key]),\r\n  mapKeys(\"SpanAttributes\")) as tags,\r\n  arrayMap(key -> map('key', key, 'value',\"ResourceAttributes\"[key]),\r\n  mapKeys(\"ResourceAttributes\")) as serviceTags\r\nFROM \"default\".\"otel_traces\"\r\nWHERE traceID = trace_id\r\n  AND startTime >= trace_start\r\n  AND startTime <= trace_end\r\nORDER BY startTime\r\nLIMIT 1000",
     "round": "0s",
     "table": "opentelemetry_span_log"
    }
   ]
  }
 ]
}