{
 "title": "Query Trace Details",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "queryId",
    "label": "queryId",
    "query": "SELECT query_id FROM otel_traces_trace_id_ts"
   },
   {
    "name": "datasource",
    "label": "datasource",
    "query": "vertamedia-clickhouse-datasource"
   }
  ]
 },
 "panels": [
  {
   "title": "Traces",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "rawQuery": "/* grafana dashboard=Query Trace Details, user=0 */\nSELECT (intDiv(toFloat64(Timestamp) * 1000, (5 * 1000)) * (5 * 1000)) as t, count() FROM default.otel_traces WHERE Timestamp >= toDateTime64(1749034472,3) AND Timestamp <= toDateTime64(1749045272,3) GROUP BY t ORDER BY t",
     "rawSql": "SELECT\r\n  min(Timestamp) as timestamp,\r\n  TraceId as `Trace ID`,\r\n  argMin(ServiceName, Timestamp) as `Service Name`,\r\n  divide(max(Duration), 1000000) as Duration\r\nFROM otel_traces\r\nWHERE\r\n  $__conditionalAll(TraceId IN (${trace_id:singlequote}),  $trace_id)\r\n  AND ServiceName IN (${serviceName:singlequote})\r\n  AND ServiceName != 'loadgenerator'\r\n  AND $__timeFilter(Timestamp)\r\nGROUP BY TraceId\r\nORDER BY Duration DESC\r\nLIMIT 100\r\n",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Traced query",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": " SELECT hostname(), \r\n        query AS sql,\r\n        query_id,\r\n      Start,\r\n      End\r\nFROM otel_traces_trace_id_ts\r\n",
     "rawQuery": "/* grafana dashboard=Query Trace Details, user=0 */\nSELECT hostname(), \r\n        query AS sql,\r\n        query_id\r\n      Start,\r\n      End\r\nFROM otel_traces_trace_id_ts",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Traced query",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM default.otel_traces_trace_id_ts WHERE query_id = '$queryId'",
     "rawQuery": "/* grafana dashboard=Query Trace Details, user=0 */\nSELECT * FROM default.otel_traces_trace_id_ts WHERE query_id = '1aa99f66-79eb-4508-8bbe-7e43abb07c75",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Trace detail",
   "type": "traces",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "system",
     "dateColDataType": "finish_date",
     "dateTimeColDataType": "start_time_us",
     "dateTimeType": "TIMESTAMP64_9",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "WITH \r\n  (SELECT min(Start) FROM \"default\".\"otel_traces_trace_id_ts\"\r\n    WHERE query_id = '$queryId') as trace_start,\r\n  (SELECT max(End) + 1 FROM \"default\".\"otel_traces_trace_id_ts\"\r\n    WHERE query_id = '$queryId') as trace_end\r\nSELECT \"TraceId\" as traceID,\r\n  \"SpanId\" as spanID,\r\n  \"ParentSpanId\" as parentSpanID,\r\n  \"ServiceName\" as serviceName,\r\n  \"SpanName\" as operationName,\r\n  \"Timestamp\" as startTime,\r\n  \"Duration\" as duration,\r\n  arrayMap(key -> map('key', key, 'value',\"SpanAttributes\"[key]),\r\n  mapKeys(\"SpanAttributes\")) as tags,\r\n  \"ResourceAttributes\" as serviceTags\r\nFROM \"default\".\"otel_traces\"\r\nWHERE TraceId IN (SELECT DISTINCT TraceId FROM otel_traces WHERE ResourceAttributes['clickhouse.initial_query_id'] = '$queryId'  OR ResourceAttributes['clickhouse.query_id'] = '$queryId') --AND   `FinishDate` = toDate(trace_end)\r\n --AND startTime >= trace_start\r\n  --AND startTime <= trace_end AND `FinishDate` = toDate(trace_end)\r\n --AND startTime >= trace_start\r\n -- AND startTime <= trace_end\r\nORDER BY startTime\r\nLIMIT 1000",
     "rawQuery": "/* grafana dashboard=Query Trace Details, user=0 */\nWITH \r\n  (SELECT min(Start) FROM \"default\".\"otel_traces_trace_id_ts\"\r\n    WHERE query_id = '1aa99f66-79eb-4508-8bbe-7e43abb07c75') as trace_start,\r\n  (SELECT max(End) + 1 FROM \"default\".\"otel_traces_trace_id_ts\"\r\n    WHERE query_id = '1aa99f66-79eb-4508-8bbe-7e43abb07c75') as trace_end\r\nSELECT \"TraceId\" as traceID,\r\n  \"SpanId\" as spanID,\r\n  \"ParentSpanId\" as parentSpanID,\r\n  \"ServiceName\" as serviceName,\r\n  \"SpanName\" as operationName,\r\n  \"Timestamp\" as startTime,\r\n  \"Duration\" as duration,\r\n  arrayMap(key -> map('key', key, 'value',\"SpanAttributes\"[key]),\r\n  mapKeys(\"SpanAttributes\")) as tags,\r\n  \"ResourceAttributes\" as serviceTags\r\nFROM \"default\".\"otel_traces\"\r\nWHERE TraceId IN (SELECT DISTINCT TraceId FROM otel_traces WHERE ResourceAttributes['clickhouse.initial_query_id'] = '1aa99f66-79eb-4508-8bbe-7e43abb07c75'  OR ResourceAttributes['clickhouse.query_id'] = '1aa99f66-79eb-4508-8bbe-7e43abb07c75') \n \n  -AND startTime <= trace_end AND `FinishDate` = toDate(trace_end)\r\n \n \nORDER BY startTime\r\nLIMIT 1000",
     "round": "0s",
     "table": "opentelemetry_span_log"
    }
   ]
  }
 ]
}